import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"node:assert",
		"node:async_hooks",
		"node:buffer",
		"node:dns",
		"node:console",
		"node:crypto",
		"node:diagnostics_channel",
		"node:events",
		"node:fs",
		"node:http",
		"node:https",
		"node:net",
		"node:path",
		"node:perf_hooks",
		"node:querystring",
		"node:stream",
		"node:string_decoder",
		"node:timers",
		"node:tls",
		"node:url",
		"node:util",
		"node:util/types",
		"node:worker_threads",
		"node:zlib",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}